S1AP-PDU {
    itu-t (0) identified-organization (4) etsi (0) mobileDomain (0)
    eps-Access (21) modules (3) s1ap (1) version1 (1)
}

DEFINITIONS AUTOMATIC TAGS ::=

BEGIN

IMPORTS
    S1ap-Criticality,
    S1ap-ProcedureCode,
    S1ap-ProtocolIE-ID
FROM S1AP-CommonDataTypes

    s1ap-maxProtocolIEs,
    s1ap-maxnoofE-RABs
FROM S1AP-Constants

    S1ap-CSGMembershipStatus,
    S1ap-CSG-Id,
    S1ap-CellAccessMode,
    S1ap-PLMNidentity,
    S1ap-IE-Extensions,
    S1ap-E-RAB-ID
FROM S1AP-IEs;


S1AP-PDU ::= CHOICE {
    initiatingMessage       S1ap-InitiatingMessage,
    successfulOutcome       S1ap-SuccessfulOutcome,
    unsuccessfulOutcome     S1ap-UnsuccessfulOutcome,
    ...
}

S1ap-InitiatingMessage ::= SEQUENCE {
    procedureCode   S1ap-ProcedureCode,
    criticality     S1ap-Criticality,
    value           ANY
}

S1ap-SuccessfulOutcome ::= SEQUENCE {
    procedureCode   S1ap-ProcedureCode,
    criticality     S1ap-Criticality,
    value           ANY
}

S1ap-UnsuccessfulOutcome ::= SEQUENCE {
    procedureCode   S1ap-ProcedureCode,
    criticality     S1ap-Criticality,
    value           ANY
}

S1ap-HandoverRequired ::= SEQUENCE {
    s1ap-HandoverRequired-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-HandoverCommand ::= SEQUENCE {
    s1ap-HandoverCommand-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-HandoverPreparationFailure ::= SEQUENCE {
    s1ap-HandoverPreparationFailure-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-HandoverRequest ::= SEQUENCE {
    s1ap-HandoverRequest-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-HandoverRequestAcknowledge ::= SEQUENCE {
    s1ap-HandoverRequestAcknowledge-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-HandoverFailure ::= SEQUENCE {
    s1ap-HandoverFailure-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-HandoverNotify ::= SEQUENCE {
    s1ap-HandoverNotify-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-PathSwitchRequest ::= SEQUENCE {
    s1ap-PathSwitchRequest-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-PathSwitchRequestAcknowledge ::= SEQUENCE {
    s1ap-PathSwitchRequestAcknowledge-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-PathSwitchRequestFailure ::= SEQUENCE {
    s1ap-PathSwitchRequestFailure-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-E-RABSetupRequest ::= SEQUENCE {
    s1ap-E-RABSetupRequest-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-E-RABSetupResponse ::= SEQUENCE {
    s1ap-E-RABSetupResponse-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-E-RABModifyRequest ::= SEQUENCE {
    s1ap-E-RABModifyRequest-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-E-RABModifyResponse ::= SEQUENCE {
    s1ap-E-RABModifyResponse-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-E-RABReleaseIndication ::= SEQUENCE {
    s1ap-E-RABReleaseIndication-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-E-RABReleaseCommand ::= SEQUENCE {
    s1ap-E-RABReleaseCommand-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-E-RABReleaseResponse ::= SEQUENCE {
    s1ap-E-RABReleaseResponse-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-InitialContextSetupRequest ::= SEQUENCE {
    s1ap-InitialContextSetupRequest-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-InitialContextSetupResponse ::= SEQUENCE {
    s1ap-InitialContextSetupResponse-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-InitialContextSetupFailure ::= SEQUENCE {
    s1ap-InitialContextSetupFailure-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-UEContextReleaseRequest ::= SEQUENCE {
    s1ap-UEContextReleaseRequest-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-Paging ::= SEQUENCE {
    s1ap-Paging-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-DownlinkNASTransport ::= SEQUENCE {
    s1ap-DownlinkNASTransport-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-InitialUEMessage ::= SEQUENCE {
    s1ap-InitialUEMessage-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-UplinkNASTransport ::= SEQUENCE {
    s1ap-UplinkNASTransport-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-NASNonDeliveryIndication ::= SEQUENCE {
    s1ap-NASNonDeliveryIndication-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-HandoverCancel ::= SEQUENCE {
    s1ap-HandoverCancel-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-HandoverCancelAcknowledge ::= SEQUENCE {
    s1ap-HandoverCancelAcknowledge-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-Reset ::= SEQUENCE {
    s1ap-Reset-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-ResetAcknowledge ::= SEQUENCE {
    s1ap-ResetAcknowledge-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-S1SetupResponse ::= SEQUENCE {
    s1ap-S1SetupResponse-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-S1SetupRequest ::= SEQUENCE {
    s1ap-S1SetupRequest-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-S1SetupFailure ::= SEQUENCE {
    s1ap-S1SetupFailure-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-ErrorIndication ::= SEQUENCE {
    s1ap-ErrorIndication-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-ENBConfigurationUpdate ::= SEQUENCE {
    s1ap-ENBConfigurationUpdate-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-ENBConfigurationUpdateAcknowledge ::= SEQUENCE {
    s1ap-ENBConfigurationUpdateAcknowledge-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-ENBConfigurationUpdateFailure ::= SEQUENCE {
    s1ap-ENBConfigurationUpdateFailure-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-MMEConfigurationUpdate ::= SEQUENCE {
    s1ap-MMEConfigurationUpdate-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-MMEConfigurationUpdateAcknowledge ::= SEQUENCE {
    s1ap-MMEConfigurationUpdateAcknowledge-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-MMEConfigurationUpdateFailure ::= SEQUENCE {
    s1ap-MMEConfigurationUpdateFailure-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-DownlinkS1cdma2000tunneling ::= SEQUENCE {
    s1ap-DownlinkS1cdma2000tunneling-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-UplinkS1cdma2000tunneling ::= SEQUENCE {
    s1ap-UplinkS1cdma2000tunneling-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-UEContextModificationRequest ::= SEQUENCE {
    s1ap-UEContextModificationRequest-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-UEContextModificationResponse ::= SEQUENCE {
    s1ap-UEContextModificationResponse-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-UEContextModificationFailure ::= SEQUENCE {
    s1ap-UEContextModificationFailure-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-UECapabilityInfoIndication ::= SEQUENCE {
    s1ap-UECapabilityInfoIndication-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-UEContextReleaseCommand ::= SEQUENCE {
    s1ap-UEContextReleaseCommand-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-UEContextReleaseComplete ::= SEQUENCE {
    s1ap-UEContextReleaseComplete-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-ENBStatusTransfer ::= SEQUENCE {
    s1ap-ENBStatusTransfer-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-MMEStatusTransfer ::= SEQUENCE {
    s1ap-MMEStatusTransfer-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-DeactivateTrace ::= SEQUENCE {
    s1ap-DeactivateTrace-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-TraceStart ::= SEQUENCE {
    s1ap-TraceStart-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-TraceFailureIndication ::= SEQUENCE {
    s1ap-TraceFailureIndication-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-CellTrafficTrace ::= SEQUENCE {
    s1ap-CellTrafficTrace-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-LocationReportingControl ::= SEQUENCE {
    s1ap-LocationReportingControl-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-LocationReportingFailureIndication ::= SEQUENCE {
    s1ap-LocationReportingFailureIndication-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-LocationReport ::= SEQUENCE {
    s1ap-LocationReport-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-OverloadStart ::= SEQUENCE {
    s1ap-OverloadStart-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-OverloadStop ::= SEQUENCE {
    s1ap-OverloadStop-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-WriteReplaceWarningRequest ::= SEQUENCE {
    s1ap-WriteReplaceWarningRequest-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-WriteReplaceWarningResponse ::= SEQUENCE {
    s1ap-WriteReplaceWarningResponse-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-ENBDirectInformationTransfer ::= SEQUENCE {
    s1ap-ENBDirectInformationTransfer-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-MMEDirectInformationTransfer ::= SEQUENCE {
    s1ap-MMEDirectInformationTransfer-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-ENBConfigurationTransfer ::= SEQUENCE {
    s1ap-ENBConfigurationTransfer-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-MMEConfigurationTransfer ::= SEQUENCE {
    s1ap-MMEConfigurationTransfer-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-PrivateMessage ::= SEQUENCE {
    s1ap-PrivateMessage-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-KillRequest ::= SEQUENCE {
    s1ap-KillRequest-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-KillResponse ::= SEQUENCE {
    s1ap-KillResponse-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-DownlinkUEAssociatedLPPaTransport ::= SEQUENCE {
    s1ap-DownlinkUEAssociatedLPPaTransport-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-UplinkUEAssociatedLPPaTransport ::= SEQUENCE {
    s1ap-UplinkUEAssociatedLPPaTransport-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-DownlinkNonUEAssociatedLPPaTransport ::= SEQUENCE {
    s1ap-DownlinkNonUEAssociatedLPPaTransport-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

S1ap-UplinkNonUEAssociatedLPPaTransport ::= SEQUENCE {
    s1ap-UplinkNonUEAssociatedLPPaTransport-ies SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}


-- **************************************************************
--
-- E-RAB MODIFICATION INDICATION ELEMENTARY PROCEDURE
--
-- **************************************************************

-- **************************************************************
--
-- E-RAB Modification Indication
--
-- **************************************************************

S1ap-E-RABModificationIndication ::= SEQUENCE {
    s1ap-E-RABModificationIndicationIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-E-RABModificationIndication ::= SEQUENCE {
--    protocolIEs         ProtocolIE-Container       { { S1ap-E-RABModificationIndicationIEs} },
--    ...
--}

--S1ap-E-RABModificationIndicationIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-MME-UE-S1AP-ID                          CRITICALITY reject  TYPE S1ap-MME-UE-S1AP-ID                     PRESENCE mandatory}|
--    { ID id-eNB-UE-S1AP-ID                          CRITICALITY reject  TYPE S1ap-ENB-UE-S1AP-ID                     PRESENCE mandatory}|
--    { ID id-E-RABToBeModifiedListBearerModInd       CRITICALITY reject  TYPE S1ap-E-RABToBeModifiedListBearerModInd      PRESENCE mandatory}|
--    { ID id-E-RABNotToBeModifiedListBearerModInd    CRITICALITY reject  TYPE S1ap-E-RABNotToBeModifiedListBearerModInd   PRESENCE optional}|
--    { ID id-CSGMembershipInfo                       CRITICALITY reject  TYPE S1ap-CSGMembershipInfo                  PRESENCE optional}|
---- Extension for Release 11 to support BBAI -- 
--    { ID id-Tunnel-Information-for-BBF              CRITICALITY ignore  TYPE S1ap-TunnelInformation                  PRESENCE optional},
--    ...
--}


S1ap-E-RABToBeModifiedListBearerModInd ::= SEQUENCE {
    s1ap-E-RABToBeModifiedItemBearerModIndIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-E-RABToBeModifiedListBearerModInd ::= E-RAB-IE-ContainerList { {S1ap-E-RABToBeModifiedItemBearerModIndIEs} }

--S1ap-E-RABToBeModifiedItemBearerModIndIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-E-RABToBeModifiedItemBearerModInd       CRITICALITY reject  TYPE S1ap-E-RABToBeModifiedItemBearerModInd      PRESENCE mandatory},
--    ...
--}

--S1ap-E-RABToBeModifiedItemBearerModInd ::= SEQUENCE {
--    e-RAB-ID                        S1ap-E-RAB-ID,
--    transportLayerAddress           S1ap-TransportLayerAddress,
--    dL-GTP-TEID                     S1ap-GTP-TEID,
--    iE-Extensions                   ProtocolExtensionContainer { { S1ap-E-RABToBeModifiedItemBearerModInd-ExtIEs} }          OPTIONAL,
--    ...
--}

--S1ap-E-RABToBeModifiedItemBearerModInd-ExtIEs S1AP-PROTOCOL-EXTENSION ::= {
--    ...
--}

S1ap-E-RABNotToBeModifiedListBearerModInd ::= SEQUENCE {
    s1ap-E-RABNotToBeModifiedItemBearerModIndIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-E-RABNotToBeModifiedListBearerModInd ::= E-RAB-IE-ContainerList { {S1ap-E-RABNotToBeModifiedItemBearerModIndIEs} }

--S1ap-E-RABNotToBeModifiedItemBearerModIndIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-E-RABNotToBeModifiedItemBearerModInd        CRITICALITY reject  TYPE S1ap-E-RABNotToBeModifiedItemBearerModInd       PRESENCE mandatory},
--    ...
--}

--S1ap-E-RABNotToBeModifiedItemBearerModInd ::= SEQUENCE {
--    e-RAB-ID                        S1ap-E-RAB-ID,
--    transportLayerAddress           S1ap-TransportLayerAddress,
--    dL-GTP-TEID                     S1ap-GTP-TEID,
--    iE-Extensions                   ProtocolExtensionContainer { { S1ap-E-RABNotToBeModifiedItemBearerModInd-ExtIEs} }       OPTIONAL,
--    ...
--}

--S1ap-E-RABNotToBeModifiedItemBearerModInd-ExtIEs S1AP-PROTOCOL-EXTENSION ::= {
--    ...
--}

S1ap-CSGMembershipInfo ::= SEQUENCE {
    cSGMembershipStatus     S1ap-CSGMembershipStatus,
    cSG-Id                  S1ap-CSG-Id,
    cellAccessMode          S1ap-CellAccessMode  OPTIONAL,
    pLMNidentity            S1ap-PLMNidentity    OPTIONAL,
    -- iE-Extensions           ProtocolExtensionContainer { { S1ap-CSGMembershipInfo-ExtIEs} }      OPTIONAL,
    iE-Extensions           S1ap-IE-Extensions      OPTIONAL,
    ...
}

--CSGMembershipInfo-ExtIEs S1AP-PROTOCOL-EXTENSION ::= {
--    ...
--}

-- **************************************************************
--
-- E-RAB Modification Confirm
--
-- **************************************************************

S1ap-E-RABModificationConfirm ::= SEQUENCE {
    s1ap-E-RABModificationConfirmIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-E-RABModificationConfirm ::= SEQUENCE {
--    protocolIEs         ProtocolIE-Container { {S1ap-E-RABModificationConfirmIEs} },
--    ...
--}

--S1ap-E-RABModificationConfirmIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-MME-UE-S1AP-ID                          CRITICALITY ignore  TYPE S1ap-MME-UE-S1AP-ID                 PRESENCE mandatory}|
--    { ID id-eNB-UE-S1AP-ID                          CRITICALITY ignore  TYPE S1ap-ENB-UE-S1AP-ID                 PRESENCE mandatory}|
--    { ID id-E-RABModifyListBearerModConf            CRITICALITY ignore  TYPE S1ap-E-RABModifyListBearerModConf   PRESENCE optional}|
--    { ID id-E-RABFailedToModifyListBearerModConf    CRITICALITY ignore  TYPE S1ap-E-RABList                      PRESENCE optional}|
--    { ID id-E-RABToBeReleasedListBearerModConf      CRITICALITY ignore  TYPE S1ap-E-RABList                      PRESENCE optional}|
--    { ID id-CriticalityDiagnostics                  CRITICALITY ignore  TYPE S1ap-CriticalityDiagnostics     PRESENCE optional}|
--    { ID id-CSGMembershipStatus                     CRITICALITY ignore  TYPE S1ap-CSGMembershipStatus            PRESENCE optional},
--    ...
--}

S1ap-E-RABModifyListBearerModConf ::= SEQUENCE (SIZE(1.. s1ap-maxnoofE-RABs)) OF S1ap-IE

--S1ap-E-RABModifyListBearerModConf ::= SEQUENCE (SIZE(1.. s1ap-maxnoofE-RABs)) OF ProtocolIE-SingleContainer { {S1ap-E-RABModifyItemBearerModConfIEs} }

--S1ap-E-RABModifyItemBearerModConfIEs     S1AP-PROTOCOL-IES ::= {
--    { ID id-E-RABModifyItemBearerModConf        CRITICALITY ignore  TYPE S1ap-E-RABModifyItemBearerModConf       PRESENCE mandatory},
--    ...
--}

S1ap-E-RABModifyItemBearerModConf ::= SEQUENCE {
    e-RAB-ID                    S1ap-E-RAB-ID,
    -- iE-Extensions               ProtocolExtensionContainer { {S1ap-E-RABModifyItemBearerModConfExtIEs} } OPTIONAL,
    iE-Extensions               S1ap-IE-Extensions OPTIONAL,
    ...
}

--S1ap-E-RABModifyItemBearerModConfExtIEs S1AP-PROTOCOL-EXTENSION ::= {
--    ...
--}

-- **************************************************************
--
-- UE CONTEXT MODIFICATION INDICATION ELEMENTARY PROCEDURE
--
-- **************************************************************

-- **************************************************************
--
-- UE Context Modification Indication
--
-- **************************************************************

S1ap-UEContextModificationIndication ::= SEQUENCE {
    s1ap-UEContextModificationIndicationIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-UEContextModificationIndication ::= SEQUENCE {
--    protocolIEs         ProtocolIE-Container       { { S1ap-UEContextModificationIndicationIEs} },
--    ...
--}

--S1ap-UEContextModificationIndicationIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-MME-UE-S1AP-ID          CRITICALITY reject  TYPE S1ap-MME-UE-S1AP-ID         PRESENCE mandatory}|
--    { ID id-eNB-UE-S1AP-ID          CRITICALITY reject  TYPE S1ap-ENB-UE-S1AP-ID         PRESENCE mandatory}|
--    { ID id-CSGMembershipInfo       CRITICALITY reject  TYPE S1ap-CSGMembershipInfo      PRESENCE optional},
--    ...
--}


-- **************************************************************
--
-- UE Context Modification Confirm
--
-- **************************************************************

S1ap-UEContextModificationConfirm ::= SEQUENCE {
    s1ap-UEContextModificationConfirmIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-UEContextModificationConfirm ::= SEQUENCE {
--    protocolIEs         ProtocolIE-Container { {S1ap-UEContextModificationConfirmIEs} },
--    ...
--}

--S1ap-UEContextModificationConfirmIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-MME-UE-S1AP-ID              CRITICALITY ignore  TYPE S1ap-MME-UE-S1AP-ID             PRESENCE mandatory}|
--    { ID id-eNB-UE-S1AP-ID              CRITICALITY ignore  TYPE S1ap-ENB-UE-S1AP-ID             PRESENCE mandatory}|
--    { ID id-CSGMembershipStatus         CRITICALITY ignore  TYPE S1ap-CSGMembershipStatus        PRESENCE optional}|
--    { ID id-CriticalityDiagnostics      CRITICALITY ignore  TYPE S1ap-CriticalityDiagnostics     PRESENCE optional},
--    ...
--}

-- **************************************************************
--
-- UE CONTEXT SUSPEND ELEMENTARY PROCEDURE
--
-- **************************************************************

-- **************************************************************
--
-- UE Context Suspend Request
--
-- **************************************************************

S1ap-UEContextSuspendRequest ::= SEQUENCE {
    s1ap-UEContextSuspendRequestIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-UEContextSuspendRequest ::= SEQUENCE {
--    protocolIEs         ProtocolIE-Container       { { S1ap-UEContextSuspendRequestIEs} },
--    ...
--}

--S1ap-UEContextSuspendRequestIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-MME-UE-S1AP-ID                                  CRITICALITY reject  TYPE S1ap-MME-UE-S1AP-ID             PRESENCE mandatory}|
--    { ID id-eNB-UE-S1AP-ID                                  CRITICALITY reject  TYPE S1ap-ENB-UE-S1AP-ID             PRESENCE mandatory}|
--    { ID id-InformationOnRecommendedCellsAndENBsForPaging   CRITICALITY ignore  TYPE S1ap-InformationOnRecommendedCellsAndENBsForPaging PRESENCE optional}|
--    { ID id-CellIdentifierAndCELevelForCECapableUEs         CRITICALITY ignore  TYPE S1ap-CellIdentifierAndCELevelForCECapableUEs    PRESENCE optional},
--    ...
--}

-- **************************************************************
--
-- UE Context Suspend Response
--
-- **************************************************************

S1ap-UEContextSuspendResponse ::= SEQUENCE {
    s1ap-UEContextSuspendResponseIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-UEContextSuspendResponse ::= SEQUENCE {
--    protocolIEs         ProtocolIE-Container { {S1ap-UEContextSuspendResponseIEs} },
--    ...
--}

--S1ap-UEContextSuspendResponseIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-MME-UE-S1AP-ID              CRITICALITY ignore  TYPE S1ap-MME-UE-S1AP-ID             PRESENCE mandatory}|
--    { ID id-eNB-UE-S1AP-ID              CRITICALITY ignore  TYPE S1ap-ENB-UE-S1AP-ID             PRESENCE mandatory}|
--    { ID id-CriticalityDiagnostics      CRITICALITY ignore  TYPE S1ap-CriticalityDiagnostics     PRESENCE optional}|
--    { ID id-SecurityContext             CRITICALITY reject  TYPE S1ap-SecurityContext            PRESENCE optional},
--    ...
--}

-- **************************************************************
--
-- UE CONTEXT RESUME ELEMENTARY PROCEDURE
--
-- **************************************************************

-- **************************************************************
--
-- UE Context Resume Request
--
-- **************************************************************

S1ap-UEContextResumeRequest ::= SEQUENCE {
    s1ap-UEContextResumeRequestIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-UEContextResumeRequest ::= SEQUENCE {
--    protocolIEs         ProtocolIE-Container       { { S1ap-UEContextResumeRequestIEs} },
--    ...
--}

--S1ap-UEContextResumeRequestIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-MME-UE-S1AP-ID                                      CRITICALITY reject  TYPE S1ap-MME-UE-S1AP-ID             PRESENCE mandatory}|
--    { ID id-eNB-UE-S1AP-ID                                  CRITICALITY reject  TYPE S1ap-ENB-UE-S1AP-ID             PRESENCE mandatory}|
--    { ID id-E-RABFailedToResumeListResumeReq                CRITICALITY reject  TYPE S1ap-E-RABFailedToResumeListResumeReq       PRESENCE optional}|
--    { ID id-RRC-Resume-Cause                                CRITICALITY ignore  TYPE S1ap-RRC-Establishment-Cause    PRESENCE optional},
--    ...
--}

S1ap-E-RABFailedToResumeListResumeReq ::= SEQUENCE {
    s1ap-E-RABFailedToResumeItemResumeReqIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}
--S1ap-E-RABFailedToResumeListResumeReq ::= E-RAB-IE-ContainerList { {S1ap-E-RABFailedToResumeItemResumeReqIEs} }

--S1ap-E-RABFailedToResumeItemResumeReqIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-E-RABFailedToResumeItemResumeReq    CRITICALITY reject  TYPE S1ap-E-RABFailedToResumeItemResumeReq   PRESENCE mandatory},
--    ...
--}

--S1ap-E-RABFailedToResumeItemResumeReq ::= SEQUENCE {
--    e-RAB-ID                            S1ap-E-RAB-ID,
--    cause                               S1ap-Cause,
--    iE-Extensions                       ProtocolExtensionContainer { { S1ap-E-RABFailedToResumeItemResumeReq-ExtIEs} }       OPTIONAL,
--    ...
--}

--S1ap-E-RABFailedToResumeItemResumeReq-ExtIEs S1AP-PROTOCOL-EXTENSION ::= {
--    ...
--}

-- **************************************************************
--
-- UE Context Resume Response
--
-- **************************************************************

S1ap-UEContextResumeResponse ::= SEQUENCE {
    s1ap-UEContextResumeResponseIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-UEContextResumeResponse ::= SEQUENCE {
--    protocolIEs         ProtocolIE-Container       { { S1ap-UEContextResumeResponseIEs} },
--    ...
--}

--S1ap-UEContextResumeResponseIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-MME-UE-S1AP-ID                      CRITICALITY ignore  TYPE S1ap-MME-UE-S1AP-ID                         PRESENCE mandatory}|
--    { ID id-eNB-UE-S1AP-ID                      CRITICALITY ignore  TYPE S1ap-ENB-UE-S1AP-ID                         PRESENCE mandatory}|
--    { ID id-E-RABFailedToResumeListResumeRes    CRITICALITY reject  TYPE S1ap-E-RABFailedToResumeListResumeRes       PRESENCE optional}|
--    { ID id-CriticalityDiagnostics              CRITICALITY ignore  TYPE S1ap-CriticalityDiagnostics                 PRESENCE optional}|
--    { ID id-SecurityContext                     CRITICALITY reject  TYPE S1ap-SecurityContext                        PRESENCE optional},
--    ...
--}

S1ap-E-RABFailedToResumeListResumeRes ::= SEQUENCE {
    s1ap-E-RABFailedToResumeItemResumeResIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-E-RABFailedToResumeListResumeRes ::= E-RAB-IE-ContainerList { {S1ap-E-RABFailedToResumeItemResumeResIEs} }

--S1ap-E-RABFailedToResumeItemResumeResIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-E-RABFailedToResumeItemResumeRes    CRITICALITY reject  TYPE S1ap-E-RABFailedToResumeItemResumeRes   PRESENCE mandatory},
--    ...
--}

--S1ap-E-RABFailedToResumeItemResumeRes ::= SEQUENCE {
--    e-RAB-ID                            S1ap-E-RAB-ID,
--    cause                               S1ap-Cause,
--    iE-Extensions                       ProtocolExtensionContainer { { S1ap-E-RABFailedToResumeItemResumeRes-ExtIEs} }       OPTIONAL,
--    ...
--}

--E-RABFailedToResumeItemResumeRes-ExtIEs S1AP-PROTOCOL-EXTENSION ::= {
--    ...
--}

-- **************************************************************
--
-- UE Context Resume Failure
--
-- **************************************************************

S1ap-UEContextResumeFailure ::= SEQUENCE {
    s1ap-UEContextResumeFailureIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-UEContextResumeFailure ::= SEQUENCE {
--    protocolIEs         ProtocolIE-Container       { { S1ap-UEContextResumeFailureIEs} },
--    ...
--}

--S1ap-UEContextResumeFailureIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-MME-UE-S1AP-ID                      CRITICALITY ignore  TYPE S1ap-MME-UE-S1AP-ID                     PRESENCE mandatory}|
--    { ID id-eNB-UE-S1AP-ID                      CRITICALITY ignore  TYPE S1ap-ENB-UE-S1AP-ID                     PRESENCE mandatory}|
--    { ID id-Cause                               CRITICALITY ignore  TYPE S1ap-Cause                              PRESENCE mandatory}|
--    { ID id-CriticalityDiagnostics              CRITICALITY ignore  TYPE S1ap-CriticalityDiagnostics             PRESENCE optional},
--    ...
--}

-- **************************************************************
--
-- Connection Establishment Indication
--
-- **************************************************************

S1ap-ConnectionEstablishmentIndication::= SEQUENCE {
    s1ap-ConnectionEstablishmentIndicationIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-ConnectionEstablishmentIndication::= SEQUENCE {
--    protocolIEs         ProtocolIE-Container { {S1ap-ConnectionEstablishmentIndicationIEs} },
--    ...
--}

--S1ap-ConnectionEstablishmentIndicationIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-MME-UE-S1AP-ID              CRITICALITY ignore  TYPE S1ap-MME-UE-S1AP-ID             PRESENCE mandatory}|
--    { ID id-eNB-UE-S1AP-ID              CRITICALITY ignore  TYPE S1ap-ENB-UE-S1AP-ID             PRESENCE mandatory}|
--    { ID id-UERadioCapability           CRITICALITY ignore  TYPE S1ap-UERadioCapability          PRESENCE optional }|
--    { ID id-EnhancedCoverageRestricted  CRITICALITY ignore  TYPE S1ap-EnhancedCoverageRestricted PRESENCE optional }|
--    { ID id-DL-CP-SecurityInformation   CRITICALITY ignore  TYPE S1ap-DL-CP-SecurityInformation  PRESENCE optional },
--    ...
--}

-- **************************************************************
--
-- Retrieve UE Information 
--
-- **************************************************************

S1ap-RetrieveUEInformation ::= SEQUENCE {
    s1ap-RetrieveUEInformationIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-RetrieveUEInformation ::= SEQUENCE {
--    protocolIEs         ProtocolIE-Container       { { S1ap-RetrieveUEInformationIEs} },
--    ...
--}

--S1ap-RetrieveUEInformationIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-S-TMSI                      CRITICALITY reject  TYPE S1ap-S-TMSI             PRESENCE mandatory},
--...
--}


-- **************************************************************

-- UE Information Transfer
--
-- **************************************************************

S1ap-UEInformationTransfer ::= SEQUENCE {
    s1ap-UEInformationTransferIEs SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-UEInformationTransfer ::= SEQUENCE {
--    protocolIEs         ProtocolIE-Container       { {  S1ap-UEInformationTransferIEs} },
--    ...
--}

--S1ap-UEInformationTransferIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-S-TMSI                      CRITICALITY reject  TYPE S1ap-S-TMSI                     PRESENCE mandatory}|
--    { ID id-UE-Level-QoS-Parameters     CRITICALITY ignore  TYPE S1ap-E-RABLevelQoSParameters    PRESENCE optional}|
--    { ID id-UERadioCapability           CRITICALITY ignore  TYPE S1ap-UERadioCapability          PRESENCE optional},
--    ...
--}


-- **************************************************************
--
-- eNB CP Relocation Indication
--
-- **************************************************************

S1ap-ENBCPRelocationIndication ::= SEQUENCE {
    s1ap-ENBCPRelocationIndication SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-ENBCPRelocationIndication ::= SEQUENCE {
--    protocolIEs         ProtocolIE-Container { { S1ap-ENBCPRelocationIndicationIEs} },
--    ...
--}

--S1ap-ENBCPRelocationIndicationIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-eNB-UE-S1AP-ID              CRITICALITY reject  TYPE S1ap-ENB-UE-S1AP-ID             PRESENCE mandatory}|
--    { ID id-S-TMSI                      CRITICALITY reject  TYPE S1ap-S-TMSI                     PRESENCE mandatory}|
--    { ID id-EUTRAN-CGI                  CRITICALITY ignore  TYPE S1ap-EUTRAN-CGI                 PRESENCE mandatory}|
--    { ID id-TAI                         CRITICALITY ignore  TYPE S1ap-TAI                        PRESENCE mandatory}|
--    { ID id-UL-CP-SecurityInformation   CRITICALITY reject  TYPE S1ap-UL-CP-SecurityInformation  PRESENCE mandatory},
--    ...
--}


-- **************************************************************
--
-- MME CP Relocation Indication
--
-- **************************************************************

S1ap-MMECPRelocationIndication ::= SEQUENCE {
    s1ap-MMECPRelocationIndication SEQUENCE (SIZE (0..s1ap-maxProtocolIEs)) OF S1ap-IE,
    ...
}

--S1ap-MMECPRelocationIndication ::= SEQUENCE {
--    protocolIEs         ProtocolIE-Container { { S1ap-MMECPRelocationIndicationIEs} },
--    ...
--}

--S1ap-MMECPRelocationIndicationIEs S1AP-PROTOCOL-IES ::= {
--    { ID id-MME-UE-S1AP-ID              CRITICALITY reject  TYPE S1ap-MME-UE-S1AP-ID             PRESENCE mandatory}|
--    { ID id-eNB-UE-S1AP-ID              CRITICALITY reject  TYPE S1ap-ENB-UE-S1AP-ID             PRESENCE mandatory},
--    ...
--}





S1ap-IE ::= SEQUENCE {
    id          S1ap-ProtocolIE-ID,
    criticality S1ap-Criticality,
    value       ANY
}

END